### ISSUE TITLE
__STDC_FORMAT_MACROS for inttypes.h on libc6-dev 2.13 (Debian Wheezy)

### ISSUE THREAD

**Issue by tilt12345678** [jcnelson/fskit#8]
I don't know how much this matters, but for the libc6-dev inttypes on Debian Wheezy (2.14-38+deb7u6) it is required to define __STDC_FORMAT_MACROS in the preprocessor to have PRIX64 et al. defined.

This is not the case in libc6-dev of Debian Jessie (2.19-13).

I am not an expert and can offer no rationale on why this changed.

**Comment by jcnelson** [comment]
Hi tilt12345678,

Thank you for bringing this to my attention!  Can you confirm that 04c0f9896e9f3fc7ddbec177106bd5bae4cebd5a fixes it?

Thanks!
